version: 2.1

orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/node:18.16
  working_directory: ~/AriaNg

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: |
            npm install
            npm run build
      - run:
          name: Create tarball of build artifacts
          command: tar -czf build-artifacts.tar.gz dist
      - store_artifacts:
          path: build-artifacts.tar.gz
          destination: build-artifacts.tar.gz
      - persist_to_workspace:
          root: ~/AriaNg
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/AriaNg
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
